// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace CqrsSample.Business.Fine.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class th2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(th2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605190604351_th2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
